### ISSUE TITLE
Strange model problem

### ISSUE THREAD

**Issue by Omgise** [makamys/SmartMoving#2]
https://user-images.githubusercontent.com/106000018/202677712-85087d32-4ea9-43ef-a949-700b6a2eb85e.mp4

**Comment by Omgise** [comment]
This is what happened in Crawling

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/makamys/SmartMoving/files/10040374/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/makamys/SmartMoving/files/10040375/fml-junk-earlystartup.log)
[latest.log](https://github.com/makamys/SmartMoving/files/10040376/latest.log)

**Comment by makamys** [comment]
This happens with SkinPort when RenderPlayerAPI is not installed; try adding [it](http://www.mediafire.com/file/txaqk31g3ooan9b/MC_1.7.10_-_Render_Player_API_core_1.4.zip).

**Comment by Omgise** [comment]
The problem is solved, thank you :D
