### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [makamys/SmartMoving#4]
Is this the smart moving mod from this link? 

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1274224-smart-moving

**Comment by tyrael93** [comment]
Technically it's a fork of the original smart moving mod you provided the link to. It has a bunch of extra bugfixes and changes.

**Comment by makamys** [comment]
Yeah, it's a fork based on Smart Moving 15.6.

**Comment by Fireworkstars46** [comment]
Also is there a discord server for the mod or no?

**Comment by makamys** [comment]
Not officially, I hang around in Et Futurum Requiem's discord though.

**Comment by Fireworkstars46** [comment]
Do I ask here or there?

**Comment by makamys** [comment]
Here is fine.

**Comment by Fireworkstars46** [comment]
Ok. So for my main question is I want to use the smart moving mod for 1.6.4 and I have it but for some reason I can't use smart moving's sprint keybind key for vanilla MC sprint speed. Is it not possible or is the sprint key only work with the genetic smart moving sprinting?

**Comment by makamys** [comment]
In the original version of Smart Moving, the sprint key activates Smart Moving's sprint. To perform the vanilla sprint, you have to double tap W.

This is something I fixed in my fork, by making it so releasing the sprint key transitions you to the vanilla sprint rather than walking. I don't intend to support versions other than 1.7.10 however, so you're out of luck there.

**Comment by Fireworkstars46** [comment]
So there's no way to use the vanilla sprint with the smart moving sprint key?

**Comment by makamys** [comment]
As far as I know, no.

**Comment by Fireworkstars46** [comment]
Would me using the smart movings sprint but changing the speed settings work?

**Comment by makamys** [comment]
I think it would, the issue is releasing the sprint key would still terminate the sprint. The vanilla sprint speed multiplier is 1.3 FYI.
