### ISSUE TITLE
spectator mode EFR breaks smart moving when pressing shift with "illegal stance" error

### ISSUE THREAD

**Issue by kotmatross28729** [makamys/SmartMoving#8]
https://user-images.githubusercontent.com/110309314/212535800-91b2c037-3b3e-42a4-91b8-9d582eafb789.mp4

the logs says: KOT had an illegal stance: 0.019999980926513672

**Comment by makamys** [comment]
Don't know why it happens, I made Smart Moving temporarily disable itself while the player is in spectator mode as a workaround.
